def get_males():
    value = [
        {'name': 'Shepard Smith', 'handle': 'ShepNewsTeam'},
        {'name': 'Trevor Noah', 'handle': 'trevornoah'},
        {'name': 'Dave Weigel', 'handle': 'daveweigel'},
        {'name': 'Sean Hannity', 'handle': 'seanhannity'},
        {'name': 'Fareed Zakaria', 'handle': 'fareedzakaria'},
        {'name': 'John Oliver', 'handle': 'iamjohnoliver'},
        {'name': 'Nicholas Kristof', 'handle': 'nickkristof'},
        {'name': 'David Frum', 'handle': 'davidfrum'},
        {'name': 'Paul Krugman', 'handle': 'paulkrugman'},
        {'name': 'David Folkenflik', 'handle': 'davidfolkenflik'},
        {'name': 'Joe Scarborough', 'handle': 'JoeNBC'},
        {'name': 'Ari Melber', 'handle': 'AriMelber'},
        {'name': 'George Will', 'handle': 'GeorgeWill'},
        {'name': 'Bernie Sanders', 'handle': 'BernieSanders'},
        {'name': 'Michael Smith', 'handle': 'michaelsmith'},
        {'name': 'Barack Obama', 'handle': 'BarackObama'},
        {'name': 'Anderson Cooper', 'handle': 'andersoncooper'},
        {'name': 'Matt Fuller', 'handle': 'MEPFuller'},
        {'name': 'Nate Silver', 'handle': 'NateSilver538'},
        {'name': 'George Stephanopoulos', 'handle': 'gstephanopoulos'},
        {'name': 'Christopher Hayes', 'handle': 'chrislhayes'},
        {'name': 'Glenn Greenwald', 'handle': 'ggreenwald'},
        {'name': 'John Dickerson', 'handle': 'jdickerson'},
        {'name': 'David Corn', 'handle': 'davidcorndc'},
        {'name': 'Robert Reich', 'handle': 'RBReich'},
        {'name': 'Jake Tapper', 'handle': 'jaketapper'},
        {'name': 'Bret Baier', 'handle': 'bretbaier'},
        {'name': 'Glenn Beck', 'handle': 'glennbeck'},
        {'name': 'Bill O\'Reilly', 'handle': 'billoreilly'},
        {'name': 'Andrew Malcolm', 'handle': 'ahmalcolm'},
        {'name': 'Charles Krauthammer', 'handle': 'krauthammer'},
        {'name': 'Ed Henry', 'handle': 'edhenry'},
        {'name': 'Brit Hume', 'handle': 'brithume'},
        {'name': 'Major Garrett', 'handle': 'majorcbs'},
        {'name': 'Greg Gutfeld', 'handle': 'greggutfeld'},
        {'name': 'Tucker Carlson', 'handle': 'tuckercarlson'},
        {'name': 'Judge Napolitano', 'handle': 'judgenap'},
        {'name': 'Jim Roberts', 'handle': 'nycjim'},
        {'name': 'Matt Taibbi', 'handle': 'mtaibbi'},
        {'name': 'Matt Yglesias', 'handle': 'mattyglesias'},
        {'name': 'Lawrence O\'Donnell', 'handle': 'lawrence'},
        {'name': 'Andy Borowitz', 'handle': 'borowitzreport'},
        {'name': 'Tavis Smiley', 'handle': 'tavissmiley'},
        {'name': 'Chris Matthews', 'handle': 'HardballChris'},
        {'name': 'Don Lemon', 'handle': 'donlemon'},
        {'name': 'Markos Moulitsas', 'handle': 'markos'},
        {'name': 'Thomas L.Friedman', 'handle': 'tomfriedman'},
        {'name': 'Chris Cuomo', 'handle': 'chriscuomo'},
        {'name': 'Reverend Al Sharpton', 'handle': 'thereval'},
        {'name': 'Andrew Sullivan', 'handle': 'sullydish'},
        {'name': 'Bill Keller', 'handle': 'billkeller2014'},
        {'name': 'Charles M.Blow', 'handle': 'charlesmblow'},
        {'name': 'Jonathan Capehart', 'handle': 'capehartj'},
        {'name':  'Ta - Nehisi Coates', 'handle': 'tanehisicoates'},
        {'name': 'Erick Erickson', 'handle': 'ewerickson'},
        {'name': 'Jonah Goldberg', 'handle': 'Jonahnro'},
        {'name': 'Neil Cavuto', 'handle': 'teamcavuto'},
        {'name': 'Robert Costa', 'handle': 'costareports'},
        {'name': 'Larry Sabato', 'handle': 'LarrySabato'},
        {'name': 'Eric Bolling', 'handle': 'ericbolling'},
        {'name': 'Rich Lowry', 'handle': 'richlowry'},
        {'name': 'Andy Levy', 'handle': 'andylevy'},
        {'name': 'Bill Hemmer', 'handle': 'billhemmer'},
        {'name': 'Dinesh D \'Souza', 'handle': 'DineshDSouza'},
        {'name': 'Fred Barnes', 'handle': 'fredbarnes'},
        {'name': 'David Burge', 'handle': 'iowahawkblog'},
        {'name': 'Brian Kilmeade', 'handle': 'kilmeade'},
    ]

    return value


def females():
    value = [
        {'name': 'Megyn Kelly', 'handle': 'megynkelly'},
        {'name': 'Samantha Bee', 'handle': 'iamsambee'},
        {'name': 'Andrea Tantaros', 'handle': 'andreatantaros'},
        {'name': 'Aparna Nancherla', 'handle': 'aparnapkin'},
        {'name': 'Tomi Lahren', 'handle': 'tomilahren'},
        {'name': 'Melissa Harris-Perry', 'handle': 'mharrisperry'},
        {'name': 'Hillary Clinton', 'handle': 'hillaryclinton'},
        {'name': 'Harris Faulkner', 'handle': 'harrisfaulkner'},
        {'name': 'Katie Couric', 'handle': 'katiecouric'},
        {'name': 'Gloria Steinem', 'handle': 'gloriasteinem'},
        {'name': 'Diane Sawyer', 'handle': 'dianesawyer'},
        {'name': 'Katy Tur', 'handle': 'katyturnbc'},
        {'name': 'Julia Ioffe', 'handle': 'juliaioffe'},
        {'name': 'Amberin Zaman', 'handle': 'amberinzaman'},
        {'name': 'Oprah Winfrey', 'handle': 'oprah'},
        {'name': 'Andrea Mitchell', 'handle': 'mitchellreports'},
        {'name': 'Lydia Cacho', 'handle': 'lydiacachosi'},
        {'name': 'Sarah Palin', 'handle': 'sarahpalinusa'},
        {'name': 'Ann Coulter', 'handle': 'anncoulter'},
        {'name': 'Rachel Maddow', 'handle': 'maddow'},
        {'name': 'Arianna Huffington', 'handle': 'ariannahuff'},
        {'name': 'Laura Ingraham', 'handle': 'ingrahamangle'},
        {'name': 'Pamela Geller', 'handle': 'pamelageller'},
        {'name': 'Donna Brazile', 'handle': 'donnabrazile'},
        {'name': 'Kirsten Powers', 'handle': 'kirstenpowers'},
        {'name': 'Michelle Obama', 'handle': 'michelleobama'},
        {'name': 'Loretta Lynch', 'handle': 'aglynch'},
        {'name': 'Betsy Devos', 'handle': 'betsydevos'},
        {'name': 'Connie Schultz', 'handle': 'connieschultz'},
        {'name': 'Kathy Griffin', 'handle': 'kathygriffin'},
        {'name': 'Mika Brzezinski', 'handle': 'morningmika'},
        {'name': 'Leslie Jones', 'handle': 'lesdoggg'},
        {'name': 'Greta Van Susteren', 'handle': 'greta'},
        {'name': 'Jemele Hill', 'handle': 'jemelehill'},
        {'name': 'Christiane Amanpour', 'handle': 'camanpour'},
        {'name': 'Ann Curry', 'handle': 'anncurry'},
        {'name': 'Michelle Malkin', 'handle': 'michellemalkin'},
        {'name': 'Dana Perino', 'handle': 'danaperino'},
        {'name': 'Dana Loesch', 'handle': 'dloesch'},
        {'name': 'S.E.Cupp', 'handle': 'secupp'},
        {'name': 'Katrina vanden Heuvel', 'handle': 'katrinanation'},
        {'name': 'Ana Marie Cox', 'handle': 'anamariecox'},
        {'name': 'Maureen Dowd', 'handle': 'maureendowd'},
        {'name': 'Kimberly Guilfoyle', 'handle': 'kimguilfoyle'},
        {'name': 'Peggy Noonan', 'handle': 'Peggynoonannyc'},
        {'name': 'Monica Crowley', 'handle': 'monicacrowley'},
        {'name': 'Mary Katharine Ham', 'handle': 'mkhammer'},
        {'name': 'Anne Bayefsky', 'handle': 'AnneBayefsky'},
        {'name': 'Martha Maccallum', 'handle': 'marthamaccallum'},
        {'name': 'Elisabeth Hasselbeck', 'handle': 'ehasselbeck'}
    ]

    return value
