def get_values(**kwargs):
    dict = [
        {'name': 'Shepard Smith', 'handle': 'ShepNewsTeam', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Trevor Noah', 'handle': 'trevornoah', 'sex': 'male', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Dave Weigel', 'handle': 'daveweigel', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Sean Hannity', 'handle': 'seanhannity', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Fareed Zakaria', 'handle': 'fareedzakaria', 'sex': 'male', 'race': 'indian', 'stance': 'neutral'},
        {'name': 'John Oliver', 'handle': 'iamjohnoliver', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Nicholas Kristof', 'handle': 'nickkristof', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'David Frum', 'handle': 'davidfrum', 'sex': 'male', 'race': 'white', 'stance': 'neoconservative'},
        {'name': 'Paul Krugman', 'handle': 'paulkrugman', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'David Folkenflik', 'handle': 'davidfolkenflik', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Joe Scarborough', 'handle': 'JoeNBC', 'sex': 'male', 'race': 'white', 'stance': 'republican'},
        {'name': 'Ari Melber', 'handle': 'AriMelber', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'George Will', 'handle': 'GeorgeWill', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Bernie Sanders', 'handle': 'BernieSanders', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Michael Smith', 'handle': 'michaelsmith', 'sex': 'male', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Barack Obama', 'handle': 'BarackObama', 'sex': 'male', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Anderson Cooper', 'handle': 'andersoncooper', 'sex': 'male', 'race': 'white', 'stance': 'neutral'},
        {'name': 'Matt Fuller', 'handle': 'MEPFuller', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Nate Silver', 'handle': 'NateSilver538', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'George Stephanopoulos', 'handle': 'gstephanopoulos', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Christopher Hayes', 'handle': 'chrislhayes', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Glenn Greenwald', 'handle': 'ggreenwald', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'John Dickerson', 'handle': 'jdickerson', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'David Corn', 'handle': 'davidcorndc', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Robert Reich', 'handle': 'RBReich', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Jake Tapper', 'handle': 'jaketapper', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Bret Baier', 'handle': 'bretbaier', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Glenn Beck', 'handle': 'glennbeck', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Bill O\'Reilly', 'handle': 'billoreilly', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Andrew Malcolm', 'handle': 'ahmalcolm', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Charles Krauthammer', 'handle': 'krauthammer', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Ed Henry', 'handle': 'edhenry', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Brit Hume', 'handle': 'brithume', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Major Garrett', 'handle': 'majorcbs', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Greg Gutfeld', 'handle': 'greggutfeld', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Tucker Carlson', 'handle': 'tuckercarlson', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Judge Napolitano', 'handle': 'judgenap', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Jim Roberts', 'handle': 'nycjim', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Matt Taibbi', 'handle': 'mtaibbi', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Matt Yglesias', 'handle': 'mattyglesias', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Lawrence O\'Donnell', 'handle': 'lawrence', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Andy Borowitz', 'handle': 'borowitzreport', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Tavis Smiley', 'handle': 'tavissmiley', 'sex': 'male', 'race': 'black', 'stance': 'unknown'},
        {'name': 'Chris Matthews', 'handle': 'HardballChris', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Don Lemon', 'handle': 'donlemon', 'sex': 'male', 'race': 'black', 'stance': 'neutral'},
        {'name': 'Markos Moulitsas', 'handle': 'markos', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Thomas L.Friedman', 'handle': 'tomfriedman', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Chris Cuomo', 'handle': 'chriscuomo', 'sex': 'male', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Reverend Al Sharpton', 'handle': 'thereval', 'sex': 'male', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Andrew Sullivan', 'handle': 'sullydish', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Bill Keller', 'handle': 'billkeller2014', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Charles M.Blow', 'handle': 'charlesmblow', 'sex': 'male', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Jonathan Capehart', 'handle': 'capehartj', 'sex': 'male', 'race': 'black', 'stance': 'liberal'},
        {'name':  'Ta - Nehisi Coates', 'handle': 'tanehisicoates', 'sex': 'male', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Erick Erickson', 'handle': 'ewerickson', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Jonah Goldberg', 'handle': 'Jonahnro', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Neil Cavuto', 'handle': 'teamcavuto', 'sex': 'male', 'race': 'white', 'stance': 'neutral'},
        {'name': 'Robert Costa', 'handle': 'costareports', 'sex': 'male', 'race': 'white', 'stance': 'neutral'},
        {'name': 'Larry Sabato', 'handle': 'LarrySabato', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Eric Bolling', 'handle': 'ericbolling', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Rich Lowry', 'handle': 'richlowry', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Andy Levy', 'handle': 'andylevy', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Bill Hemmer', 'handle': 'billhemmer', 'sex': 'male', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Dinesh D \'Souza', 'handle': 'DineshDSouza', 'sex': 'male', 'race': 'indian', 'stance': 'conservative'},
        {'name': 'Fred Barnes', 'handle': 'fredbarnes', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'David Burge', 'handle': 'iowahawkblog', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Brian Kilmeade', 'handle': 'kilmeade', 'sex': 'male', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Megyn Kelly', 'handle': 'megynkelly', 'sex': 'female', 'race': 'white', 'stance': 'nuetral'},
        {'name': 'Samantha Bee', 'handle': 'iamsambee', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Andrea Tantaros', 'handle': 'andreatantaros', 'sex': 'female', 'race': 'asian', 'stance': 'conservative'},
        {'name': 'Aparna Nancherla', 'handle': 'aparnapkin', 'sex': 'female', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Tomi Lahren', 'handle': 'tomilahren', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Melissa Harris-Perry', 'handle': 'mharrisperry', 'sex': 'female', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Hillary Clinton', 'handle': 'hillaryclinton', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Harris Faulkner', 'handle': 'harrisfaulkner', 'sex': 'female', 'race': 'black', 'stance': 'conservative'},
        {'name': 'Katie Couric', 'handle': 'katiecouric', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Gloria Steinem', 'handle': 'gloriasteinem', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Diane Sawyer', 'handle': 'dianesawyer', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Katy Tur', 'handle': 'katyturnbc', 'sex': 'female', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Julia Ioffe', 'handle': 'juliaioffe', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Amberin Zaman', 'handle': 'amberinzaman', 'sex': 'female', 'race': 'middle eastern', 'stance': 'unknown'},
        {'name': 'Oprah Winfrey', 'handle': 'oprah', 'sex': 'female', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Andrea Mitchell', 'handle': 'mitchellreports', 'sex': 'female', 'race': 'white', 'stance': 'democrat'},
        {'name': 'Lydia Cacho', 'handle': 'lydiacachosi', 'sex': 'female', 'race': 'hispanic', 'stance': 'unknown'},
        {'name': 'Sarah Palin', 'handle': 'sarahpalinusa', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Ann Coulter', 'handle': 'anncoulter', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Rachel Maddow', 'handle': 'maddow', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Arianna Huffington', 'handle': 'ariannahuff', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Laura Ingraham', 'handle': 'ingrahamangle', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Pamela Geller', 'handle': 'pamelageller', 'sex': 'female', 'race': 'white', 'stance': 'anti-islam'},
        {'name': 'Donna Brazile', 'handle': 'donnabrazile', 'sex': 'female', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Kirsten Powers', 'handle': 'kirstenpowers', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Michelle Obama', 'handle': 'michelleobama', 'sex': 'female', 'race': 'black', 'stance': 'democrat'},
        {'name': 'Loretta Lynch', 'handle': 'aglynch', 'sex': 'female', 'race': 'black', 'stance': 'democrat'},
        {'name': 'Betsy Devos', 'handle': 'betsydevos', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Connie Schultz', 'handle': 'connieschultz', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Kathy Griffin', 'handle': 'kathygriffin', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Mika Brzezinski', 'handle': 'morningmika', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Leslie Jones', 'handle': 'lesdoggg', 'sex': 'female', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Greta Van Susteren', 'handle': 'greta', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Jemele Hill', 'handle': 'jemelehill', 'sex': 'female', 'race': 'black', 'stance': 'liberal'},
        {'name': 'Christiane Amanpour', 'handle': 'camanpour', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Ann Curry', 'handle': 'anncurry', 'sex': 'female', 'race': 'asian', 'stance': 'liberal'},
        {'name': 'Michelle Malkin', 'handle': 'michellemalkin', 'sex': 'female', 'race': 'asian', 'stance': 'conservative'},
        {'name': 'Dana Perino', 'handle': 'danaperino', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Dana Loesch', 'handle': 'dloesch', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'S.E.Cupp', 'handle': 'secupp', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Katrina vanden Heuvel', 'handle': 'katrinanation', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Ana Marie Cox', 'handle': 'anamariecox', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Maureen Dowd', 'handle': 'maureendowd', 'sex': 'female', 'race': 'white', 'stance': 'liberal'},
        {'name': 'Kimberly Guilfoyle', 'handle': 'kimguilfoyle', 'sex': 'female', 'race': 'hispanic', 'stance': 'conservative'},
        {'name': 'Peggy Noonan', 'handle': 'Peggynoonannyc', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Monica Crowley', 'handle': 'monicacrowley', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Mary Katharine Ham', 'handle': 'mkhammer', 'sex': 'female', 'race': 'white', 'stance': 'conservative'},
        {'name': 'Anne Bayefsky', 'handle': 'AnneBayefsky', 'sex': 'female', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Martha Maccallum', 'handle': 'marthamaccallum', 'sex': 'female', 'race': 'white', 'stance': 'unknown'},
        {'name': 'Elisabeth Hasselbeck', 'handle': 'ehasselbeck', 'sex': 'female', 'race': 'white', 'stance': 'conservative'}
    ]

    if not kwargs:
        return dict

    redux = []
    for subject in dict:
        all_keys_correct = False
        for key, value in kwargs.items():
            if key in subject and subject[key] == value:
                all_keys_correct = True
            else:
                all_keys_correct = False
                break

        if all_keys_correct:
            redux.append(subject)

    return redux
