def get_values(**kwargs):
    dict = [
        {
            "birth_year": "1970",
            "followers": "2406172",
            "handle": "megynkelly",
            "id": "",
            "job": "journalist/news anchor",
            "join_date": "2/1/2010",
            "name": "Megyn Kelly",
            "network": "nbc news (was fox)",
            "race": "white",
            "sex": "female",
            "stance": "neutral"
        },
        {
            "birth_year": "1964",
            "followers": "214237",
            "handle": "ShepNewsTeam",
            "id": "169203819",
            "job": "news anchor",
            "join_date": "7/1/2010",
            "name": "Shepard Smith",
            "network": "fox news",
            "race": "white",
            "sex": "male(gay)",
            "stance": "liberal"
        },
        {
            "birth_year": "1984",
            "followers": "7656225",
            "handle": "trevornoah",
            "id": "46335511",
            "job": "tv host/comedian",
            "join_date": "6/1/2009",
            "name": "Trevor Noah",
            "network": "",
            "race": "black(south african)",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1969",
            "followers": "472762",
            "handle": "iamsambee",
            "id": "",
            "job": "tv host/comedian",
            "join_date": "3/11/2017",
            "name": "Samantha Bee",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1978",
            "followers": "505607",
            "handle": "andreatantaros",
            "id": "",
            "job": "political analyst",
            "join_date": "4/1/2009",
            "name": "Andrea Tantaros",
            "network": "formerly fox news",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1982",
            "followers": "258099",
            "handle": "aparnapkin",
            "id": "",
            "job": "comedian",
            "join_date": "1/1/2008",
            "name": "Aparna Nancherla",
            "network": "",
            "race": "southeast asian",
            "sex": "female",
            "stance": "unknown"
        },
        {
            "birth_year": "1992",
            "followers": "845616",
            "handle": "tomilahren",
            "id": "",
            "job": "political commentator",
            "join_date": "1/1/2012",
            "name": "Tomi Lahren",
            "network": "theblaze",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1981",
            "followers": "349465",
            "handle": "daveweigel",
            "id": "13524182",
            "job": "journalist/news anchor",
            "join_date": "9/1/2008",
            "name": "Dave Weigel",
            "network": "washington post",
            "race": "white",
            "sex": "male",
            "stance": "unknown"
        },
        {
            "birth_year": "1961",
            "followers": "2900653",
            "handle": "seanhannity",
            "id": "41634520",
            "job": "news anchor",
            "join_date": "5/1/2009",
            "name": "Sean Hannity",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1964",
            "followers": "888905",
            "handle": "fareedzakaria",
            "id": "41814169",
            "job": "columnist/tv host",
            "join_date": "5/1/2009",
            "name": "Fareed Zakaria",
            "network": "cnn",
            "race": "southeast asian(indian)",
            "sex": "male",
            "stance": "neutral"
        },
        {
            "birth_year": "1973",
            "followers": "695384",
            "handle": "mharrisperry",
            "id": "",
            "job": "tv host/political commentator",
            "join_date": "1/1/2009",
            "name": "Melissa Harris-Perry",
            "network": "",
            "race": "black",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1947",
            "followers": "18724544",
            "handle": "hillaryclinton",
            "id": "",
            "job": "politician",
            "join_date": "4/1/2013",
            "name": "Hillary Clinton",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1977",
            "followers": "4364128",
            "handle": "iamjohnoliver",
            "id": "316389142",
            "job": "tv host/comedian",
            "join_date": "6/1/2011",
            "name": "John Oliver",
            "network": "hbo",
            "race": "white(british)",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1965",
            "followers": "199453",
            "handle": "harrisfaulkner",
            "id": "",
            "job": "newscaster",
            "join_date": "12/1/2008",
            "name": "Harris Faulkner",
            "network": "fox news",
            "race": "black",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1957",
            "followers": "1798080",
            "handle": "katiecouric",
            "id": "",
            "job": "journalist/news anchor",
            "join_date": "1/1/2009",
            "name": "Katie Couric",
            "network": "yahoo! global",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1934",
            "followers": "285860",
            "handle": "gloriasteinem",
            "id": "",
            "job": "journalist/activist",
            "join_date": "6/1/2009",
            "name": "Gloria Steinem",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1945",
            "followers": "902267",
            "handle": "dianesawyer",
            "id": "",
            "job": "journalist/news anchor",
            "join_date": "4/1/2011",
            "name": "Diane Sawyer",
            "network": "formerly abc news",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1983",
            "followers": "386305",
            "handle": "katyturnbc",
            "id": "",
            "job": "journalist",
            "join_date": "5/1/2009",
            "name": "Katy Tur",
            "network": "nbc news",
            "race": "white",
            "sex": "female",
            "stance": "unknown"
        },
        {
            "birth_year": "1982",
            "followers": "143338",
            "handle": "juliaioffe",
            "id": "",
            "job": "journalist",
            "join_date": "9/1/2009",
            "name": "Julia Ioffe",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "",
            "followers": "333479",
            "handle": "amberinzaman",
            "id": "",
            "job": "journalist",
            "join_date": "9/1/2009",
            "name": "Amberin Zaman",
            "network": "",
            "race": "middle eastern(turkish)",
            "sex": "female",
            "stance": "unknown"
        },
        {
            "birth_year": "1954",
            "followers": "39073735",
            "handle": "oprah",
            "id": "",
            "job": "tv host",
            "join_date": "1/1/2009",
            "name": "Oprah Winfrey",
            "network": "",
            "race": "black",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1946",
            "followers": "1494872",
            "handle": "mitchellreports",
            "id": "",
            "job": "journalist",
            "join_date": "11/1/2009",
            "name": "Andrea Mitchell",
            "network": "nbc news",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1963",
            "followers": "1233171",
            "handle": "lydiacachosi",
            "id": "",
            "job": "journalist",
            "join_date": "2/1/2010",
            "name": "Lydia Cacho",
            "network": "",
            "race": "hispanic(mexican)",
            "sex": "female",
            "stance": "unknown"
        },
        {
            "birth_year": "1964",
            "followers": "1472183",
            "handle": "sarahpalinusa",
            "id": "",
            "job": "politician",
            "join_date": "8/1/2009",
            "name": "Sarah Palin",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1961",
            "followers": "1712783",
            "handle": "anncoulter",
            "id": "",
            "job": "political commentator",
            "join_date": "9/1/2010",
            "name": "Ann Coulter",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1973",
            "followers": "8420802",
            "handle": "maddow",
            "id": "",
            "job": "political commentator",
            "join_date": "9/1/2008",
            "name": "Rachel Maddow",
            "network": "msnbc",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1950",
            "followers": "2812153",
            "handle": "ariannahuff",
            "id": "",
            "job": "author",
            "join_date": "2/1/2009",
            "name": "Arianna Huffington",
            "network": "huff. post",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1963",
            "followers": "1758966",
            "handle": "ingrahamangle",
            "id": "",
            "job": "political commentator",
            "join_date": "6/1/2009",
            "name": "Laura Ingraham",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1958",
            "followers": "162854",
            "handle": "pamelageller",
            "id": "",
            "job": "political commentator",
            "join_date": "7/1/2008",
            "name": "Pamela Geller",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1959",
            "followers": "649630",
            "handle": "donnabrazile",
            "id": "",
            "job": "political analyst",
            "join_date": "7/1/2009",
            "name": "Donna Brazile",
            "network": "",
            "race": "black",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1967",
            "followers": "252744",
            "handle": "kirstenpowers",
            "id": "",
            "job": "political analyst",
            "join_date": "4/1/2008",
            "name": "Kirsten Powers",
            "network": "cnn",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1964",
            "followers": "9135140",
            "handle": "michelleobama",
            "id": "",
            "job": "former first lady of the us",
            "join_date": "11/1/2011",
            "name": "Michelle Obama",
            "network": "",
            "race": "black",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1959",
            "followers": "136219",
            "handle": "aglynch",
            "id": "",
            "job": "former attorney general of the us",
            "join_date": "5/1/2015",
            "name": "Loretta Lynch",
            "network": "",
            "race": "black",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1958",
            "followers": "146095",
            "handle": "betsydevos",
            "id": "",
            "job": "us secretary of education",
            "join_date": "2/1/2017",
            "name": "Betsy Devos",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1959",
            "followers": "2129165",
            "handle": "nickkristof",
            "id": "17004618",
            "job": "journalist",
            "join_date": "10/1/2008",
            "name": "Nicholas Kristof",
            "network": "ny times",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1960",
            "followers": "538756",
            "handle": "davidfrum",
            "id": "18686907",
            "job": "political commentator",
            "join_date": "1/1/2009",
            "name": "David Frum",
            "network": "book about bush",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1953",
            "followers": "3583097",
            "handle": "paulkrugman",
            "id": "",
            "job": "economist",
            "join_date": "",
            "name": "Paul Krugman",
            "network": "ny times",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "",
            "followers": "70788",
            "handle": "davidfolkenflik",
            "id": "",
            "job": "reporter",
            "join_date": "",
            "name": "David Folkenflik",
            "network": "npr",
            "race": "white",
            "sex": "male",
            "stance": "unknown"
        },
        {
            "birth_year": "1957",
            "followers": "34870",
            "handle": "connieschultz",
            "id": "",
            "job": "writer/journalist",
            "join_date": "",
            "name": "Connie Schultz",
            "network": "pulitzer winner/married to sharad brown who's a senator",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1960",
            "followers": "2085914",
            "handle": "kathygriffin",
            "id": "",
            "job": "comedian",
            "join_date": "",
            "name": "Kathy Griffin",
            "network": "cnn",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1967",
            "followers": "729694",
            "handle": "morningmika",
            "id": "",
            "job": "journalist",
            "join_date": "",
            "name": "Mika Brzezinski",
            "network": "msnbc",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1963",
            "followers": "1793077",
            "handle": "JoeNBC",
            "id": "",
            "job": "former us representative and talk show host",
            "join_date": "",
            "name": "Joe Scarborough",
            "network": "msnbc",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1967",
            "followers": "759517",
            "handle": "lesdoggg",
            "id": "",
            "job": "comedian",
            "join_date": "",
            "name": "Leslie Jones",
            "network": "",
            "race": "black",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1954",
            "followers": "1197520",
            "handle": "greta",
            "id": "",
            "job": "news anchor",
            "join_date": "",
            "name": "Greta Van Susteren",
            "network": "cnn->fox->nbc news",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1980",
            "followers": "237431",
            "handle": "AriMelber",
            "id": "",
            "job": "journalist",
            "join_date": "",
            "name": "Ari Melber",
            "network": "nbc news",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1941",
            "followers": "129155",
            "handle": "GeorgeWill",
            "id": "",
            "job": "commentator/columnist",
            "join_date": "",
            "name": "George Will",
            "network": "washington post / nbc news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1941",
            "followers": "8119895",
            "handle": "BernieSanders",
            "id": "",
            "job": "politician",
            "join_date": "11/1/2010",
            "name": "Bernie Sanders",
            "network": "",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1975",
            "followers": "760624",
            "handle": "jemelehill",
            "id": "",
            "job": "sport commentator",
            "join_date": "",
            "name": "Jemele Hill",
            "network": "espn",
            "race": "black",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1979",
            "followers": "487977",
            "handle": "michaelsmith",
            "id": "",
            "job": "sport commentator",
            "join_date": "",
            "name": "Michael Smith",
            "network": "espn",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1961",
            "followers": "95642271",
            "handle": "BarackObama ",
            "id": "",
            "job": "politician",
            "join_date": "3/1/2007",
            "name": "Barack Obama",
            "network": "",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1967",
            "followers": "9591467",
            "handle": "andersoncooper ",
            "id": "",
            "job": "tv host",
            "join_date": "6/1/2008",
            "name": "Anderson Cooper",
            "network": "cnn",
            "race": "white",
            "sex": "male",
            "stance": "neutral"
        },
        {
            "birth_year": "",
            "followers": "84137",
            "handle": "MEPFuller",
            "id": "",
            "job": "journalist",
            "join_date": "10/1/2011",
            "name": "Matt Fuller",
            "network": "huffpost",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1978",
            "followers": "2588570",
            "handle": "NateSilver538",
            "id": "",
            "job": "journalist",
            "join_date": "8/1/2008",
            "name": "Nate Silver",
            "network": "five thirty eight",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1961",
            "followers": "2634575",
            "handle": "gstephanopoulos",
            "id": "",
            "job": "tv anchor",
            "join_date": "10/1/2008",
            "name": "George Stephanopoulos",
            "network": "abc",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1958",
            "followers": "2446456",
            "handle": "camanpour",
            "id": "",
            "job": "tv host",
            "join_date": "8/1/2009",
            "name": "Christiane Amanpour ",
            "network": "cnn",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1956",
            "followers": "1647348",
            "handle": "anncurry",
            "id": "",
            "job": "news anchor",
            "join_date": "2/1/2009",
            "name": "Ann Curry",
            "network": "nbc",
            "race": "japanese- american",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1979",
            "followers": "1399679",
            "handle": "chrislhayes",
            "id": "",
            "job": "tv host",
            "join_date": "4/1/2009",
            "name": "Christopher Hayes",
            "network": "msnbc",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1967",
            "followers": "907673",
            "handle": "ggreenwald",
            "id": "",
            "job": "journalist",
            "join_date": "9/1/2008",
            "name": "Glenn Greenwald",
            "network": "the intercept",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1968",
            "followers": "2216034",
            "handle": "jdickerson",
            "id": "",
            "job": "journalist",
            "join_date": "4/1/2007",
            "name": "John Dickerson",
            "network": "cbs",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1959",
            "followers": "537143",
            "handle": "davidcorndc",
            "id": "",
            "job": "journalist",
            "join_date": "6/1/2008",
            "name": "David Corn",
            "network": "mother jones",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1946",
            "followers": "504706",
            "handle": "RBReich",
            "id": "",
            "job": "political commentator",
            "join_date": "5/1/2010",
            "name": "Robert Reich",
            "network": "inequality media",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1969",
            "followers": "1406218",
            "handle": "jaketapper",
            "id": "",
            "job": "anchor",
            "join_date": "4/1/2008",
            "name": "Jake Tapper",
            "network": "cnn",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1970",
            "followers": "2163025",
            "handle": "michellemalkin",
            "id": "",
            "job": "political commentator",
            "join_date": "8/1/2008",
            "name": "Michelle Malkin",
            "network": "conservative columnist tv",
            "race": "filipino",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1972",
            "followers": "1694653",
            "handle": "danaperino",
            "id": "",
            "job": "political commentator ",
            "join_date": "3/1/2009",
            "name": "Dana Perino ",
            "network": "fox news",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1970",
            "followers": "1127634",
            "handle": "bretbaier",
            "id": "",
            "job": "political anchor",
            "join_date": "1/1/2009",
            "name": "Bret Baier ",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1964",
            "followers": "1199113",
            "handle": "glennbeck",
            "id": "",
            "job": "political commentator",
            "join_date": "11/1/2008",
            "name": "Glenn Beck",
            "network": "",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1949",
            "followers": "2057",
            "handle": "billoreilly",
            "id": "",
            "job": "political commentator",
            "join_date": "3/1/2009",
            "name": "Bill O'Reilly ",
            "network": "",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1943",
            "followers": "159947",
            "handle": "ahmalcolm",
            "id": "",
            "job": "political commentator",
            "join_date": "4/1/2008",
            "name": "Andrew Malcolm ",
            "network": "ny times",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1950",
            "followers": "877356",
            "handle": "krauthammer",
            "id": "",
            "job": "political commentator",
            "join_date": "3/1/2009",
            "name": "Charles Krauthammer ",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1971",
            "followers": "261866",
            "handle": "edhenry",
            "id": "",
            "job": "journalist",
            "join_date": "9/1/2008",
            "name": "Ed Henry ",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1978",
            "followers": "631732",
            "handle": "dloesch",
            "id": "",
            "job": "political commentator",
            "join_date": "7/1/2007",
            "name": "Dana Loesch ",
            "network": "the blaze",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1943",
            "followers": "771343",
            "handle": "brithume",
            "id": "",
            "job": "journalist",
            "join_date": "2/1/2010",
            "name": "Brit Hume",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1979",
            "followers": "374510",
            "handle": "secupp",
            "id": "",
            "job": "political commentator",
            "join_date": "1/1/2009",
            "name": "S.E. Cupp",
            "network": "hln",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1962",
            "followers": "181485",
            "handle": "majorcbs",
            "id": "",
            "job": "journalist",
            "join_date": "6/1/2009",
            "name": "Major Garrett ",
            "network": "cbs",
            "race": "white",
            "sex": "male",
            "stance": "unknown"
        },
        {
            "birth_year": "1964",
            "followers": "855060",
            "handle": "greggutfeld",
            "id": "",
            "job": "political commentator/ commedian",
            "join_date": "4/1/2009",
            "name": "Greg Gutfeld ",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1969",
            "followers": "1177672",
            "handle": "tuckercarlson",
            "id": "",
            "job": "political commentator",
            "join_date": "3/1/2009",
            "name": "Tucker Carlson ",
            "network": "fox news",
            "race": "white",
            "sex": "male ",
            "stance": "conservative"
        },
        {
            "birth_year": "1950",
            "followers": "503483",
            "handle": "judgenap",
            "id": "",
            "job": "journalist",
            "join_date": "4/1/2009",
            "name": "Judge Napolitano ",
            "network": "fox news",
            "race": "italian",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1959",
            "followers": "182109",
            "handle": "katrinanation",
            "id": "",
            "job": "editor/ publisher",
            "join_date": "7/1/2009",
            "name": "Katrina vanden Heuvel ",
            "network": "the nation",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "",
            "followers": "204844",
            "handle": "nycjim",
            "id": "",
            "job": "editor",
            "join_date": "5/1/2008",
            "name": "Jim Roberts ",
            "network": "reuters/ mashable",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1970",
            "followers": "332203",
            "handle": "mtaibbi",
            "id": "",
            "job": "journalist",
            "join_date": "5/1/2009",
            "name": "Matt Taibbi ",
            "network": "rolling stones",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1981",
            "followers": "349536",
            "handle": "mattyglesias",
            "id": "",
            "job": "journalist/ blogger",
            "join_date": "7/1/2008",
            "name": "Matt Yglesias ",
            "network": "center for american progress",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1951",
            "followers": "2211914",
            "handle": "lawrence",
            "id": "",
            "job": "tv host",
            "join_date": "6/1/2010",
            "name": "Lawrence O'Donnell ",
            "network": "msnbc",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1964",
            "followers": "346337",
            "handle": "tavissmiley",
            "id": "",
            "job": "tv host",
            "join_date": "12/1/2007",
            "name": "Tavis Smiley ",
            "network": "pbs",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1945",
            "followers": "761821",
            "handle": "HardballChris",
            "id": "",
            "job": "tv host",
            "join_date": "6/1/2009",
            "name": "Chris Matthews",
            "network": "msnbc",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1966",
            "followers": "549199",
            "handle": "donlemon",
            "id": "",
            "job": "tv host",
            "join_date": "8/1/2008",
            "name": "Don Lemon ",
            "network": "cnn",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1971",
            "followers": "171182",
            "handle": "markos",
            "id": "",
            "job": "blogger",
            "join_date": "3/1/2009",
            "name": "Markos Moulitsas ",
            "network": "daily kos",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1953",
            "followers": "819987",
            "handle": "tomfriedman",
            "id": "",
            "job": "journalist",
            "join_date": "7/1/2009",
            "name": "Thomas L. Friedman ",
            "network": "ny times",
            "race": "white",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1972",
            "followers": "1364111",
            "handle": "anamariecox",
            "id": "",
            "job": "journalist",
            "join_date": "12/1/2007",
            "name": "Ana Marie Cox",
            "network": "ny times",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1970",
            "followers": "1260446",
            "handle": "chriscuomo",
            "id": "",
            "job": "tv host",
            "join_date": "3/1/2009",
            "name": "Chris Cuomo",
            "network": "cnn",
            "race": "italian",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1954",
            "followers": "545584",
            "handle": "thereval",
            "id": "",
            "job": "activist/ radio host",
            "join_date": "5/1/2009",
            "name": "Reverend Al Sharpton ",
            "network": "national action network",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1963",
            "followers": "120965",
            "handle": "sullydish",
            "id": "",
            "job": "journalist",
            "join_date": "7/1/2011",
            "name": "Andrew Sullivan ",
            "network": "new york magazine",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1949",
            "followers": "66539",
            "handle": "billkeller2014",
            "id": "",
            "job": "journalist",
            "join_date": "5/1/2009",
            "name": "Bill Keller ",
            "network": "the marshall project",
            "race": "white",
            "sex": "male",
            "stance": "unknown"
        },
        {
            "birth_year": "1970",
            "followers": "401132",
            "handle": "charlesmblow",
            "id": "",
            "job": "journalist",
            "join_date": "2/1/2009",
            "name": "Charles M. Blow ",
            "network": "ny times",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1952",
            "followers": "637499",
            "handle": "maureendowd",
            "id": "",
            "job": "journalist",
            "join_date": "7/1/2009",
            "name": "Maureen Dowd ",
            "network": "ny times",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1967",
            "followers": "261363",
            "handle": "capehartj",
            "id": "",
            "job": "journalist",
            "join_date": "12/1/2009",
            "name": "Jonathan Capehart",
            "network": "washington post",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1975",
            "followers": "1092634",
            "handle": "tanehisicoates",
            "id": "",
            "job": "journliast",
            "join_date": "5/1/2014",
            "name": "Ta-Nehisi Coates ",
            "network": "the atlantic",
            "race": "black",
            "sex": "male",
            "stance": "liberal"
        },
        {
            "birth_year": "1975",
            "followers": "187557",
            "handle": "ewerickson",
            "id": "",
            "job": "radio host/ blogger",
            "join_date": "1/1/2007",
            "name": "Erick Erickson ",
            "network": "wsb radio",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1969",
            "followers": "1265839",
            "handle": "kimguilfoyle",
            "id": "",
            "job": "tv host",
            "join_date": "3/1/2009",
            "name": "Kimberly Guilfoyle",
            "network": "fox news",
            "race": "puerto rican irish american",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1969",
            "followers": "258264",
            "handle": "Jonahnro",
            "id": "",
            "job": "columnist",
            "join_date": "9/1/2009",
            "name": "Jonah Goldberg ",
            "network": "national review",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1958",
            "followers": "554104",
            "handle": "teamcavuto",
            "id": "",
            "job": "anchor/ editor",
            "join_date": "12/1/2010",
            "name": "Neil Cavuto ",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1950",
            "followers": "161822",
            "handle": "Peggynoonannyc",
            "id": "",
            "job": "author/ speechwriter",
            "join_date": "4/1/2009",
            "name": "Peggy Noonan",
            "network": "wall street journal",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1968",
            "followers": "453314",
            "handle": "monicacrowley",
            "id": "",
            "job": "commentator/ lobbyist",
            "join_date": "7/1/2010",
            "name": "Monica Crowley ",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1985",
            "followers": "330983",
            "handle": "costareports",
            "id": "",
            "job": "journalist",
            "join_date": "10/1/2009",
            "name": "Robert Costa",
            "network": "pbs",
            "race": "white",
            "sex": "male",
            "stance": "neutral"
        },
        {
            "birth_year": "1952",
            "followers": "118714",
            "handle": "LarrySabato",
            "id": "",
            "job": "political analyst",
            "join_date": "2/1/2009",
            "name": "Larry Sabato ",
            "network": "crystal ball",
            "race": "white",
            "sex": "male",
            "stance": "unknown"
        },
        {
            "birth_year": "1980",
            "followers": "210335",
            "handle": "mkhammer",
            "id": "",
            "job": "journalist",
            "join_date": "4/1/2007",
            "name": "Mary Katharine Ham ",
            "network": "cnn",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "1963",
            "followers": "781012",
            "handle": "ericbolling",
            "id": "",
            "job": "political commentator",
            "join_date": "5/1/2008",
            "name": "Eric Bolling ",
            "network": "",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1968",
            "followers": "141746",
            "handle": "richlowry",
            "id": "",
            "job": "columnist",
            "join_date": "5/1/2009",
            "name": "Rich Lowry",
            "network": "national review",
            "race": "white",
            "sex": "male ",
            "stance": "conservative"
        },
        {
            "birth_year": "1966",
            "followers": "223824",
            "handle": "andylevy",
            "id": "",
            "job": "commentator/ writer",
            "join_date": "7/1/2007",
            "name": "Andy Levy ",
            "network": "cnn",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1964",
            "followers": "300585",
            "handle": "billhemmer",
            "id": "",
            "job": "journalist",
            "join_date": "2/1/2009",
            "name": "Bill Hemmer ",
            "network": "fox news",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1953",
            "followers": "213688",
            "handle": "AnneBayefsky",
            "id": "",
            "job": "scholar",
            "join_date": "7/1/2011",
            "name": "Anne Bayefsky ",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "unknown"
        },
        {
            "birth_year": "1964",
            "followers": "363550",
            "handle": "marthamaccallum",
            "id": "",
            "job": "newscaster",
            "join_date": "6/1/2009",
            "name": "Martha Maccallum ",
            "network": "fox news",
            "race": "white",
            "sex": "female",
            "stance": "unknown"
        },
        {
            "birth_year": "1961",
            "followers": "633941",
            "handle": "DineshDSouza",
            "id": "",
            "job": "political commentator",
            "join_date": "11/1/2009",
            "name": "Dinesh D'Souza ",
            "network": "",
            "race": "indian",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1943",
            "followers": "80526",
            "handle": "fredbarnes",
            "id": "",
            "job": "political commentator",
            "join_date": "8/1/2008",
            "name": "Fred Barnes ",
            "network": "the weekly standard",
            "race": "white",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1977",
            "followers": "401904",
            "handle": "ehasselbeck",
            "id": "",
            "job": "tv host",
            "join_date": "3/1/2009",
            "name": "Elisabeth Hasselbeck",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "conservative"
        },
        {
            "birth_year": "",
            "followers": "171909",
            "handle": "iowahawkblog",
            "id": "",
            "job": "blogger",
            "join_date": "5/1/2010",
            "name": "David Burge ",
            "network": "iowahawk",
            "race": "",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1964",
            "followers": "278892",
            "handle": "kilmeade",
            "id": "",
            "job": "tv host",
            "join_date": "6/1/2009",
            "name": "Brian Kilmeade ",
            "network": "fox news",
            "race": "irish/ italian",
            "sex": "male",
            "stance": "conservative"
        },
        {
            "birth_year": "1968",
            "followers": "326087",
            "handle": "AshleyJudd",
            "id": "",
            "job": "actress",
            "join_date": "2/1/2011",
            "name": "Ashley Judd",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1975",
            "followers": "363289",
            "handle": "AsiaArgento",
            "id": "",
            "job": "actress",
            "join_date": "1/1/2011",
            "name": "Asia Argento",
            "network": "",
            "race": "italian",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1971",
            "followers": "76314",
            "handle": "ClaireAForlani",
            "id": "",
            "job": "actress",
            "join_date": "11/1/2013",
            "name": "Claire Forlani",
            "network": "",
            "race": "italian",
            "sex": "female",
            "stance": "liberal"
        },
        {
            "birth_year": "1982",
            "followers": "79905",
            "handle": "britmarling",
            "id": "",
            "job": "actress",
            "join_date": "3/1/2009",
            "name": "Brit Marling",
            "network": "",
            "race": "white",
            "sex": "female",
            "stance": "liberal"
        }
    ]

    if not kwargs:
        return dict

    redux = []
    for subject in dict:
        all_keys_correct = False
        for key, value in kwargs.items():
            if key in subject and subject[key] == value:
                all_keys_correct = True
            else:
                all_keys_correct = False
                break

        if all_keys_correct:
            redux.append(subject)

    return redux
